include:
  - 'https://gitlab.com/colisweb-open-source/ci-common/raw/v9.4.2/templates/scala.yml'
  - 'https://gitlab.com/colisweb-open-source/ci-common/raw/v9.4.2/services/redis.yml'

variables:
  SBT_OPTS: "-Dsbt.global.base=sbt-cache/sbtboot -Dsbt.boot.directory=sbt-cache/boot -Dsbt.ivy.home=sbt-cache/ivy"
  COURSIER_CACHE: "sbt-cache/coursier"
cache:
  key: "sbt-$CI_BUILD_REF_NAME"
  paths:
    - sbt-cache

compile:
  extends: .sbt-compile
  tags: []

.test-scala-distances:
  extends:
    - .sbt-test
    - .redis
  tags: []

test core:
  extends: .test-scala-distances

test tests:
  extends: .test-scala-distances

version:
  extends: .version
  tags: []

publish on bintray:
  extends: .bintray-publish
  tags: []